name: Build and deploy Python app to Azure Web App - jobbcoach-chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv antenv
          source antenv/bin/activate
          pip install --index-url https://download.pytorch.org/whl/cpu -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BF196C8F2EE949A49932B94B6E701652 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_72EDC9807B2841F9823C1A51D6A9E474 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6DAA7FD49C24A2884131E4F659754AF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: jobbcoach-chatbot
          resource-group: jobbcoach-rg
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}